<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\News;
use App\Models\Category;
use App\Models\User;

class NewsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $techCategory = Category::where('slug', 'technology')->first();
        $businessCategory = Category::where('slug', 'business')->first();
        $environmentCategory = Category::where('slug', 'environment')->first();
        $sportsCategory = Category::where('slug', 'sports')->first();
        $cultureCategory = Category::where('slug', 'culture')->first();
        $politicsCategory = Category::where('slug', 'politics')->first();

        $authors = User::pluck('id')->toArray();

        $newsData = [
            [
                'title' => "Technological Innovation at the Heart of Government Priorities",
                'slug' => 'technological-innovation-government-priorities',
                'content' => "The government has announced a series of measures to support technological innovation in strategic sectors. This comprehensive initiative aims to position the nation as a leader in emerging technologies, with particular focus on artificial intelligence, renewable energy, and biotechnology. Industry experts have welcomed these developments, noting that they come at a crucial time for maintaining competitive advantage in the global marketplace.",
                'thumbnail' => "https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=2020",
                'category_id' => $techCategory->id,
                'published_at' => now()->subDays(1),
                'is_premium' => false,
            ],
            [
                'title' => "New Economic Reform: What Will Change for Businesses",
                'slug' => 'new-economic-reform-businesses',
                'content' => "The new economic reform promises to simplify administrative procedures and reduce tax pressure on small and medium enterprises. Business owners across the country are analyzing the implications of these changes, which include streamlined licensing processes, reduced bureaucratic red tape, and targeted tax incentives for companies investing in innovation and workforce development.",
                'thumbnail' => "https://images.unsplash.com/photo-1638913662380-9799def8ffb1?q=80&w=2070",
                'category_id' => $businessCategory->id,
                'published_at' => now()->subDays(2),
                'is_premium' => false,
            ],
            [
                'title' => "Climate Change: Experts Sound the Alarm",
                'slug' => 'climate-change-experts-alarm',
                'content' => "A new study reveals the acceleration of global warming and its consequences on the world ecosystem. The research, conducted by leading climate scientists, presents compelling evidence of rising temperatures, melting ice caps, and increasingly extreme weather events. The findings underscore the urgent need for coordinated international action to address this existential threat.",
                'thumbnail' => "https://images.unsplash.com/photo-1569163139599-0f4517e48069?q=80&w=2071",
                'category_id' => $environmentCategory->id,
                'published_at' => now()->subDays(3),
                'is_premium' => true,
            ],
            [
                'title' => "World Cup: The Favorites for the Next Edition",
                'slug' => 'world-cup-favorites-next-edition',
                'content' => "As the next World Cup approaches, experts are sharing their predictions on the favorite teams. Traditional powerhouses are facing challenges from emerging nations, creating what analysts predict will be one of the most competitive tournaments in history. Fans worldwide are eagerly anticipating the spectacle.",
                'thumbnail' => "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?q=80&w=1935",
                'category_id' => $sportsCategory->id,
                'published_at' => now()->subDays(4),
                'is_premium' => false,
            ],
            [
                'title' => "Art Market Disrupted by Artificial Intelligence",
                'slug' => 'art-market-artificial-intelligence',
                'content' => "Works generated by artificial intelligence are challenging the traditional foundations of contemporary art. Galleries and collectors are grappling with fundamental questions about authorship, creativity, and value in an era where machines can produce aesthetically compelling works. The debate has sparked intense discussion in the art world.",
                'thumbnail' => "https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=2071",
                'category_id' => $cultureCategory->id,
                'published_at' => now()->subDays(5),
                'is_premium' => false,
            ],
            [
                'title' => "Presidential Elections: Key Platforms of the Candidates",
                'slug' => 'presidential-elections-key-platforms',
                'content' => "With months to go before the elections, discover the main proposals of candidates on major issues. From healthcare reform to economic policy, education to foreign affairs, the candidates present starkly different visions for the country's future. Voters are carefully examining these platforms as they prepare to make their choice.",
                'thumbnail' => "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?q=80&w=2070",
                'category_id' => $politicsCategory->id,
                'published_at' => now()->subDays(6),
                'is_premium' => true,
            ],
            [
                'title' => "Latest AI Advances Revolutionize Medicine",
                'slug' => 'ai-advances-revolutionize-medicine',
                'content' => "AI algorithms now allow for detection of certain diseases with unprecedented accuracy, paving the way for new therapeutic approaches. Medical professionals are increasingly integrating these tools into their practice, leading to earlier diagnoses and more personalized treatment plans. The implications for patient outcomes are profound.",
                'thumbnail' => "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?q=80&w=2070",
                'category_id' => $techCategory->id,
                'published_at' => now()->subDays(7),
                'is_premium' => false,
            ],
            [
                'title' => "Real Estate Sector Faces New Urban Challenges",
                'slug' => 'real-estate-new-urban-challenges',
                'content' => "Urban densification and environmental issues are progressively transforming the real estate market in major cities. Developers are responding with innovative solutions that balance the need for housing with sustainability concerns. The shift is reshaping skylines and neighborhoods across metropolitan areas.",
                'thumbnail' => "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=2073",
                'category_id' => $businessCategory->id,
                'published_at' => now()->subDays(8),
                'is_premium' => false,
            ],
            [
                'title' => "Economic Growth Up 2.5% in First Quarter",
                'slug' => 'economic-growth-first-quarter',
                'content' => "Figures recently published by the Statistics Institute show a significant improvement in the national economy. The robust growth exceeds analysts' expectations and suggests a strong recovery trajectory. Key sectors driving this expansion include technology, manufacturing, and services.",
                'thumbnail' => "https://images.unsplash.com/photo-1579621970588-a35d0e7ab9b6?q=80&w=2070",
                'category_id' => $businessCategory->id,
                'published_at' => now()->subDays(9),
                'is_premium' => false,
            ],
            [
                'title' => "Inflation: Measures Announced to Protect Purchasing Power",
                'slug' => 'inflation-measures-purchasing-power',
                'content' => "Faced with rising prices, the government unveils its plan to support households and stabilize the economy. The comprehensive package includes energy vouchers, price caps on essential goods, and targeted assistance for vulnerable populations. Economists are divided on the long-term effectiveness of these interventions.",
                'thumbnail' => "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=2070",
                'category_id' => $businessCategory->id,
                'published_at' => now()->subDays(10),
                'is_premium' => true,
            ],
            [
                'title' => "Startups Raised 10 Billion in Funding in 2025",
                'slug' => 'startups-raised-funding-2025',
                'content' => "A historic record for the innovation ecosystem confirms its international attractiveness. Venture capital firms from around the world are increasingly looking to invest in the thriving startup scene. The funding boom reflects confidence in the region's entrepreneurial talent and market potential.",
                'thumbnail' => "https://images.unsplash.com/photo-1559136555-9303baea8ebd?q=80&w=2070",
                'category_id' => $businessCategory->id,
                'published_at' => now()->subDays(11),
                'is_premium' => false,
            ],
            [
                'title' => "Stock Market: Financial Markets Surge After Central Bank Announcement",
                'slug' => 'stock-market-central-bank-announcement',
                'content' => "The decision to maintain interest rates was favorably received by investors worldwide, causing a significant rise in major stock indices. Market analysts attribute the positive reaction to reduced uncertainty about monetary policy direction. The rally extended across multiple sectors and geographic regions.",
                'thumbnail' => "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=2070",
                'category_id' => $businessCategory->id,
                'published_at' => now()->subDays(12),
                'is_premium' => false,
            ],
            [
                'title' => "International Trade: Historic Agreement Between EU and Asia Signed",
                'slug' => 'international-trade-eu-asia-agreement',
                'content' => "This trade partnership will open new markets for European companies and strengthen economic exchanges. The agreement establishes common standards for sustainable development while reducing trade barriers. Business leaders are optimistic about the opportunities for expansion and collaboration.",
                'thumbnail' => "https://images.unsplash.com/photo-1566996533071-2c578085e257?q=80&w=2070",
                'category_id' => $businessCategory->id,
                'published_at' => now()->subDays(13),
                'is_premium' => true,
            ],
            [
                'title' => "Employment: Unemployment Rate Reaches 15-Year Low",
                'slug' => 'employment-unemployment-15-year-low',
                'content' => "Latest statistics show significant improvement in the job market with job creation in several key sectors. Technology and green transition industries are leading the hiring surge. The strong employment numbers are boosting consumer confidence and driving economic momentum.",
                'thumbnail' => "https://images.unsplash.com/photo-1521791055366-0d553872125f?q=80&w=2069",
                'category_id' => $businessCategory->id,
                'published_at' => now()->subDays(14),
                'is_premium' => false,
            ],
        ];

        foreach ($newsData as $news) {
            News::create([
                'title' => $news['title'],
                'slug' => $news['slug'],
                'content' => $news['content'],
                'thumbnail' => $news['thumbnail'],
                'user_id' => $authors[array_rand($authors)],
                'category_id' => $news['category_id'],
                'published_at' => $news['published_at'],
                'is_premium' => $news['is_premium'],
            ]);
        }
    }
}

